### ISSUE TITLE
What does this do?  Is this a foundation to build another mod or datapack?

### ISSUE THREAD

**Issue by allanonmage** [RussDev7/Optimized-Beacon-Bonus#1]
What does this do?  Is this a foundation to build another mod or datapack?  I'm leaning towards the latter, but I'm not sure.

**Comment by RussDev7** [comment]
This datapack simply allows mobs to be effected by a beacon. It includes a ton of customizations such as custom ranges and a defined list of mobs.

**Comment by specialTT** [comment]
How do you detect whether the beacon is activated?
